# Generated by Django 4.2 on 2023-06-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_creation_available_pizza_available_topping_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_category', to='pizza.category'),
        ),
    ]
