# Generated by Django 4.2 on 2023-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_creation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
