# Generated by Django 4.2 on 2023-06-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_creation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pizza_category', to='pizza.category'),
        ),
        migrations.AlterField(
            model_name='creation',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_creation', to='pizza.pizza'),
        ),
    ]
