# Generated by Django 4.2 on 2023-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_creation_category_alter_creation_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='toppings',
            field=models.ManyToManyField(blank=True, default=None, related_name='toppings_creation', to='pizza.topping'),
        ),
    ]
