# Generated by Django 4.2 on 2023-07-09 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_completed_date',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_completed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0.0, verbose_name='Total price')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.ManyToManyField(blank=True, default=None, related_name='order_cart', to='pizza.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('created_at',),
            },
        ),
    ]
